[build]
  publish = "."

[[headers]]
  for = "/*"
  [headers.values]
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://www.google-analytics.com https://pagead2.googlesyndication.com https://monetag.com https://*.monetag.com https://ads.monetag.com https://cdn.monetag.com https://fpyf8.com; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://monetag.com https://*.monetag.com; img-src 'self' data: https: http: blob:; font-src 'self' https://fonts.gstatic.com; connect-src 'self' https://www.google-analytics.com https://analytics.google.com https://monetag.com https://*.monetag.com https://ads.monetag.com https://fpyf8.com wss: ws:; frame-src 'self' https://monetag.com https://*.monetag.com; object-src 'none'; base-uri 'self'; form-action 'self'; frame-ancestors 'none';"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
